#  
# EpargneBundle/Ressources/routing.yml;
#
# Copyright 2015 GILLARDEAU Thibaut (aka Thibautg16)
#
# Authors :
#  - Gillardeau Thibaut (aka Thibautg16)
#

epargne_compte_liste:
    path:  /epargne/compte/liste
    defaults: { _controller: EpargneBundle:Compte:liste}