#  
# EpargneBundle/Ressources/routing.yml;
#
# Copyright 2015 GILLARDEAU Thibaut (aka Thibautg16)
#
# Authors :
#  - Gillardeau Thibaut (aka Thibautg16)
#

epargne_accueil:
    path:  /
    defaults: { _controller: EpargneBundle:Epargne:accueil}

epargne_compte_liste:
    path:  /epargne/compte/liste
    defaults: { _controller: EpargneBundle:Compte:liste}

epargne_compte_modifier:
    path:  /epargne/compte/modifier/{idCompte}
    defaults: { _controller: EpargneBundle:Compte:modifier}

epargne_compte_mescomptes:
    path:  /epargne/compte/mescomptes
    defaults: { _controller: EpargneBundle:Compte:mescomptes}

epargne_compte_graph:
    path:  /epargne/compte/graph/{idCompte}
    defaults: { _controller: EpargneBundle:Compte:graph}

epargne_compte_ajaxgraph:
    path:  /epargne/compte/graph
    defaults: { _controller: EpargneBundle:Compte:graphajax}

epargne_ligne_liste:
    path:  /epargne/ligne/liste/{idCompte}
    defaults: { _controller: EpargneBundle:Ligne:liste}    

epargne_ligne_valider:
    path:  /epargne/ligne/valider/{idLigne}
    defaults: { _controller: EpargneBundle:Ligne:valider}

epargne_ligne_modifier:
    path:  /epargne/ligne/modifier/{idLigne}
    defaults: { _controller: EpargneBundle:Ligne:modifier}

epargne_ligne_ajouter:
    path:  /epargne/ligne/ajouter/{idCompte}
    defaults: { _controller: EpargneBundle:Ligne:ajouter}

epargne_ligne_importer:
    path:  /epargne/ligne/importer/{idCompte}
    defaults: { _controller: EpargneBundle:Ligne:importer}