<?php

namespace EpargneBundle\Entity;

/**
 * EpargneCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpargneCompteRepository extends \Doctrine\ORM\EntityRepository {
}