<?php

namespace EpargneBundle\Entity;

/**
 * EpargneLigneCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpargneLigneCompteRepository extends \Doctrine\ORM\EntityRepository {
	
	public function myTotalGainColone($idCompte, $colone, $debPeriode, $finPeriode){
			$queryBuilder = $this->createQueryBuilder('a');
				
			$queryBuilder
			->select('SUM(a.montant), a.id, a.'.$colone)
			->where('a.compte = :idCompte')
			->andWhere('a.dateValeur BETWEEN :debPeriode AND :finPeriode')
			->setParameter('idCompte', $idCompte)
		    ->setParameter('debPeriode', $debPeriode)
			->setParameter('finPeriode', $finPeriode)
			->groupBy('a.'.$colone);
			
			// On récupère la Query à partir du QueryBuilder
			$query = $queryBuilder->getQuery();
				
			// On récupère et retourne le resultat
			return $query->getResult();				
	}
}